Add Length and Count related attributes
Qowaiv/qowaiv-validation pull request #76
Opened 2024-06-16 12:55 UTC by Corniel

The `System.ComponentModel.DataAnnotations` namespace contains multiple attributes to check for collection sizes and (string)lengths. Naming is - however - not intuitive, and messages do not clearly distinct between lengths and the number of elements.

For validation lengths:

* `[Length,AtLeast(minimum)]`
* `[Length,AtMost(maximum)]`
* `[Length.InRange(minimum, maximum)]`

For collections I'm thinking of the same naming but with `Collection.` instead of `Length.`.

2024-06-17 06:56 UTC, cmpsb commented on src/Qowaiv.Validation.DataAnnotations/QowaivValidationMessages.nl.resx
> +    <value>De lengte van het veld  {0} moet minstens {1} zijn.</value>
```suggestion
    <value>De lengte van het veld {0} moet minstens {1} zijn.</value>
```

2024-06-27 07:15 UTC, LauraXiulan requested changes

2024-06-27 07:21 UTC, Corniel commented on src/Qowaiv.Validation.DataAnnotations/QowaivValidationMessages.nl.resx
> +    <value>De lengte van het veld {1} moet tussen de {1} en {2} zijn.</value>
Goed gespot!

2024-06-27 07:23 UTC, Corniel commented on src/Qowaiv.Validation.DataAnnotations/Attributes/Size.InRangeAttribute.cs
> +            || size == StreamSize.Zero
I'll add comments: zero legnth should be dealt with by mandatory/required.

2024-06-27 07:23 UTC, Corniel commented on src/Qowaiv.Validation.DataAnnotations/Attributes/Size.AtLeastAttribute.cs
> +            || size == StreamSize.Zero
see above.

2024-06-27 07:24 UTC, Corniel commented on src/Qowaiv.Validation.DataAnnotations/Attributes/Collection.cs
> +        ICollection collection => collection.Count,
There is no none-generic interface. Is handled by the next case. (via reflection).

2024-06-27 07:53 UTC, LauraXiulan approved these changes

2024-06-27 08:37 UTC, merged